# Generated by Django 5.0.2 on 2024-02-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(related_name='category_contents', to='contents.contentcategory'),
        ),
    ]
